-- Script PostgreeSQL

CREATE TABLE PESSOA
( CODIGOPESSOA SERIAL PRIMARY KEY,
  NOME VARCHAR(50) NOT NULL,
  ENDERECO VARCHAR(50) NOT NULL,
  BAIRRO VARCHAR(32) NOT NULL,
  CIDADE VARCHAR(32) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL,
  UF VARCHAR(2) NOT NULL,
  SEXO VARCHAR(12) NOT NULL
);


CREATE TABLE DESCRICAO (	
   CODIGODESCRICAO SERIAL PRIMARY KEY,
   CODIGOPESSOA INTEGER NOT NULL,   
   DESCRICAO VARCHAR(250) NOT NULL
);


CREATE TABLE OBJETIVO_PROFISSIONAL (	
  CODIGOOBJPROFISSIONAL SERIAL PRIMARY KEY NOT NULL,
  CODIGOPESSOA INTEGER NOT NULL,  
  ESCOLARIDADE VARCHAR(32) NOT NULL,
  AREAATUACAO VARCHAR(32) NOT NULL,
  PRETENSAOSALARIAL VARCHAR(32) NOT NULL,
  CARGODESEJAVEL VARCHAR(32) NOT NULL
);


ALTER TABLE DESCRICAO
ADD CONSTRAINT FK_CODIGOPESSOADESCRICAO FOREIGN KEY (CODIGOPESSOA) REFERENCES PESSOA(CODIGOPESSOA) ON DELETE CASCADE

ALTER TABLE OBJETIVO_PROFISSIONAL
ADD CONSTRAINT FK_OBJPROFISSIONAL FOREIGN KEY (CODIGOPESSOA) REFERENCES PESSOA(CODIGOPESSOA) ON DELETE CASCADE